//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagiFiler.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class FilerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FilerSettings defaultInstance = ((FilerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FilerSettings())));
        
        public static FilerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHiddenFiles {
            get {
                return ((bool)(this["ShowHiddenFiles"]));
            }
            set {
                this["ShowHiddenFiles"] = value;
            }
        }
    }
}
